/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:fcbf1b17-ac66-4ec6-bac4-b293ca8ea69a",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_2aEhwry5h",
    "aws_user_pools_web_client_id": "3k6mjj41m54oocghnrkckj6va5",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://4vqarbcq7vbdrfuygzttotswra.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-hiuw3ykj3bc3haluedyn5w5nnu",
    "aws_user_files_s3_bucket": "amplifyappf68914e3704e4b24936c0345740e492b81236-amplifyapp",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};


export default awsmobile;
